# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"# local.py
DEBUG = True
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "1234"
test contribution 2026-02-25
test contribution 2026-02-25
test contribution 2026-02-25
test contribution 2026-02-25
test contribution 2026-02-25
test contribution 2026-02-25